version: '3.8'

networks:
  app-network:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: node-backend
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
    networks:
      - app-network